### ISSUE TITLE
Resource leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/libsxg#59]
Stream is opened
https://github.com/google/libsxg/blob/eb7a4fb0c520a8012d4271f5c2057a65d1c1416a/src/gencertchain.c#L103

Opened file never closed
https://github.com/google/libsxg/blob/eb7a4fb0c520a8012d4271f5c2057a65d1c1416a/src/gencertchain.c#L122

**Comment by gaul** [comment]
I assume @QiAnXinCodeSafe is an automated code bot.  It seems to misunderstand `__attribute__ ((__noreturn__))` on `exit`; when the process exits it implicitly closes fds.
