### ISSUE TITLE
CMAKE error when following instructions in README.txt

### ISSUE THREAD

**Issue by cpapazian** [google/libsxg#93]
even when specifying `CMAKE_INSTALL_PREFIX`, i get this error:
```
CMake Error at CMakeLists.txt:151 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "sxg".
```
including a `CMAKE_INSTALL_LIBDIR` fixes, so it looks like the documentation change made in https://github.com/google/libsxg/commit/1559f01723a0c0c31ccf3951ce09d3f9a09bc532 is innacturate.

**Comment by cpapazian** [comment]
@twifkak

**Comment by cpapazian** [comment]
appears that i was running an old cmake. works with 3.19.4

**Comment by twifkak** [comment]
Ah, good to know. I'll add [`cmake_minimum_required`](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html) to add a warning for versions <3.19.4 (with a comment to maybe lower the minimum).

**Comment by twifkak** [comment]
Actually I'll do 3.13 per the comments in CMakeLists.txt.

**Comment by twifkak** [comment]
Oh, I can't even. It's already there: https://github.com/google/libsxg/blob/8beb4dea2c7f5db85c24290bfb2c2924a3cc1c60/CMakeLists.txt#L64-L69

So I guess those numbers need to be raised.

**Comment by twifkak** [comment]
Or perhaps you needed to `rm build/CMakeCache.txt`? I'll close, but reopen if you're sure it's not that and your version was newer than the existing minimums.

**Comment by cpapazian** [comment]
this was part of the bazel build for envoy, so CMakeCache.txt was not present. also, RUN_TEST is disabled, so the min version was getting 3.0. i think upping those to 3.13 is probably sufficient
